Feature/blc 48 capture point service call
project-march/march-iv pull request #582
Opened 2020-08-25 07:34 UTC by RutgerVanBeek

Closes BLC-48

## Description

I created a new PR, because a lot was done since the start of that PR and all comments and the description were outdated. Also credits to @JorisWeeda and @Roelemans who also did a lot of the work. 

In this PR the new inverted Pendulum based capture point calculation is used by the balance gait. There is now just one capture point calculating object (not relating to one of the feet anymore). A service call is implemented to request the capture point from the capture point calculator. This is then used to set a pose goal for the swing leg in the balance gait. Goals are now set via `JointStates` as the API seems to handle them better. 
## Changes

* Remove the dependency on a foot and tf for the capture point calculatore
* Implement a service call for requesting a capture point calculation
* Update the `BalanceGait` object the handle the new flow. 
* Check for the balance parameter in the gait selection, so no object is created when the parameter is false
## Testing
Checkout this branch and set the `balance:=true` when launching. Checkout `feature/start-balance-open-with-ankle-forward-movement` and `feature/turn-off-com-plugin` for the full falling experience.

2020-08-25 10:07 UTC, JorisWeeda commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        capture_point_duration = min(duration, 0.5 * falling_time)
why do we multiple the falling time with 0.5?

2020-08-25 10:10 UTC, JorisWeeda commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +            rospy.logdebug_throttle(1, 'Cannot calculate capture point; z of new center of mass <= 0')
We state that the capture point cannot be calculated but we do move on (also in the `get_capture_point` we do not verify if this condition is true) maybe add a return statement? or create a boolean which states that it is verified?

2020-08-25 10:19 UTC, JorisWeeda commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            return None
shouldn't we return the default subgait instead of none? Not sure what the behavior will be if it reaches this statement, will the movegroup do anything?

2020-08-25 10:24 UTC, JorisWeeda commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        balance_trajectory_duration = min(sg_duration, cp_duration)
Im not so sure about this `min` anymore. Moveit! states that it would plan the trajectory as fast as the limits allow it to be . If this duration is larger compared to the subgait duration it should not be scaled otherwise the limits would be surpassed. The only thing is in practice we experience different behavior. Maybe add an extra comment, what do u guys think?

2020-08-25 10:26 UTC, JorisWeeda reviewed
I like what I see! nice cleaning and I think the method is much better implemented. Some general question, furthermore looks good. Approve is close :fire:

2020-08-25 10:57 UTC, RutgerVanBeek commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        capture_point_duration = min(duration, 0.5 * falling_time)
I thought this was more of a heuristic, with the falling time you are too late. May be @Roelemans knows more about this.

2020-08-25 15:37 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        balance_trajectory_duration = min(sg_duration, cp_duration)
I don't know exactly what was the idea here, but if the falling time is much larger then the gait time, I wouldn't go as fast as possible.

2020-08-25 15:50 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            return None
It would return a duration if successful, so I think I will return -1 (invalid duration)

2020-08-26 07:32 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        capture_point_duration = min(duration, 0.5 * falling_time)
Indeed; The falling time is the time when the CoM hits the ground, so obviously you have to be faster than that. However, it might be need to make it a constant; something like `FRACTION_OF_FALLING` or something

2020-08-26 13:51 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        balance_trajectory_duration = min(sg_duration, cp_duration)
The sg_duration is the duration of a normal swing gait, not the duration of what MoveIt produces. I think this min is fine, at most you will want to check whether this result is smaller than the duration of the MoveIt gait, and throw an error if it is (because MoveIt should already be max speed). However, since MoveIt doesn't work yet, we can at most add a comment about this as you mentioned.

2020-08-26 17:11 UTC, Roelemans requested changes

2020-08-26 17:11 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        self.cp_publisher.publish(self._capture_point_marker)
Why return the capture point duration while the capture point marker is written to a class variable? I think you should either return both or write both to a class variable

2020-08-26 17:11 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +            self.vx, self.vy, capture_point_duration)
You need the location of the CoM here relative to the stable foot. (i.e. the xyz coordinates in an axis system where the stable foot is at (0,0,0))

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            get_active_joints()
```suggestion
        self._joint_state_target.name = self.move_group['left_leg'].get_active_joints() + 
                                                          self.move_group['right_leg'].get_active_joints()
```
better to split after/before a `+`

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
>          :param subgait_name: the normal subgait name
Add a a dostring about the return value here :)

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        sg_duration = self.set_stance_leg_target(capture_point_leg_name, subgait_name)
Maybe a bit more descriptive name then sg? just write out stance_gait_duration?

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            get_active_joints()
I think it will be good to verify one last time whether the joint orders are still consistent. (once cp calculation is fixed ;))

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        rospy.loginfo('Balance subgait with duration {dr}'.format(dr=str(balance_trajectory_duration)))
```suggestion
        # Write produced subgait to file for easy evaluating
        rospy.loginfo('Balance subgait with duration {dr}'.format(dr=str(balance_trajectory_duration)))
```

2020-08-26 17:11 UTC, Roelemans commented on march_shared_resources/srv/CapturePointPose.srv
> +# Service for getting the position of the center of mass after falling for time duration
```suggestion
# Service for getting the position of the capture point, after letting the center of mass falling for time duration (this time can be used to make a step)
```

2020-08-26 17:11 UTC, Roelemans commented on march_shared_resources/srv/CapturePointPose.srv
> +bool success
What is succes? Maybe make the name more descriptive? (e.g. "capture_point_exists")

2020-08-26 17:11 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/gait_selection.py
> +            self._load_balance_gait()
```suggestion
        is_balance_used = rospy.get_param('/balance', False)
        if is_balance_used:
            self._load_balance_gait()
```

2020-08-26 19:17 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            get_active_joints()
I am pretty sure the order is consistent, because it is the order of the chain.

2020-08-26 19:18 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        rospy.loginfo('Balance subgait with duration {dr}'.format(dr=str(balance_trajectory_duration)))
I will add a docstring to the method, I think that makes more sense.

2020-08-27 08:55 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +            wt_translation = world_transform.transform.translation
```suggestion
            static_foot_transform = self._tf_buffer.lookup_transform('world', self._static_foot_link, rospy.Time())
            static_foot_position = world_transform.transform.translation
```
I think something like this is more intuitive

2020-08-27 08:55 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +            rospy.logdebug('Error in trying to lookup transform for capture point: {error}'.format(error=e))
```suggestion
            rospy.loginfo(Error in trying to lookup transform for capture point: {error}'.format(error=e))
```

2020-08-27 08:55 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +                return -1
Hmm you retrun -1 here, won't that error since you expect two outputs below?

2020-08-27 08:55 UTC, Roelemans commented on march_shared_resources/srv/CapturePointPose.srv
> +bool success
:eyes:

2020-08-27 09:13 UTC, Roelemans commented
There is something wrong with the capture point calculation; the capture point of right_open_1 is placed to the left of the left leg, though it obviously shouldn't be there. We should have a look at this together I think

2020-08-27 09:23 UTC, Roelemans commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            get_active_joints()
This is right_open_2
![image](https://user-images.githubusercontent.com/47626418/91422424-715de880-e857-11ea-914e-db3dee6123e5.png)
and this is the output of moveit
![image](https://user-images.githubusercontent.com/47626418/91422502-85094f00-e857-11ea-9efb-afbb52917c09.png)
pretty sure that something is going wrong :s

2020-08-27 13:26 UTC, RutgerVanBeek commented on march_shared_resources/srv/CapturePointPose.srv
> +bool success
Oopsie

2020-08-27 13:42 UTC, RutgerVanBeek commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +                return -1
Ah, the two outputs is new, you are right.

2020-08-31 08:25 UTC, RutgerVanBeek commented on march_shared_resources/srv/CapturePointPose.srv
> +bool success
After giving it some thought, I now think that succes describes what we mean. Did  the calculation succeed or not. `capture_point_exists` does not really cover it in my opinion as there are multiple reasons why the calculation may not have been successful, some unrelated to capture point. Let me know what you think

2020-08-31 08:59 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +            get_active_joints()
Found the bug and fixed it. Now the final positions do exactly correspond for the left leg. For the right leg it also looks quite similar. Nevertheless it is still falling of course :(

2020-08-31 10:08 UTC, Roelemans requested changes

2020-08-31 10:08 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        self._center_of_mass = updated_center_of_mass.pose.position
```suggestion
        self._center_of_mass = copy.deepcopy(updated_center_of_mass.pose.position)
```
This deepcopy was here with a reason :innocent: (don't forget to add the import)

2020-09-02 13:07 UTC, Roelemans requested changes
Capture point is looking good now! :D I always get a `Error setting joint target. Is the target within bounds?` now though :cry:. We can just leave that as an issue for M6 though ;)

2020-09-02 13:07 UTC, Roelemans commented on march_data_collector/src/march_data_collector/cp_calculator.py
> +        self.vy = 0
```suggestion
        self.com_vx = 0
        self.com_vy = 0
```
self.x,y,z are unused

2020-09-05 15:24 UTC, RutgerVanBeek commented
> Capture point is looking good now! :D I always get a `Error setting joint target. Is the target within bounds?` now though . We can just leave that as an issue for M6 though ;)

Hmmm, may be if I have some time upcoming week I will look into it.

2020-09-07 19:02 UTC, Roelemans requested changes
Good work :)

2020-09-07 19:03 UTC, Roelemans approved these changes, later dismissed
When you try so hard... :musical_note:

2020-09-11 10:31 UTC, JorisWeeda commented on march_shared_resources/srv/CapturePointPose.srv
> +bool success
I agree with Rutger.

2020-09-11 10:32 UTC, JorisWeeda submitted a review, later dismissed
:fire: nice work boys

2020-09-18 13:19 UTC, Roelemans reviewed
I always get a "Error setting joint target. Is the target within bounds?" :cry: Dunno what could be the problem :s

2020-09-23 13:39 UTC, Roelemans approved these changes
Whoopsie forgot to pull. Seems to work properly! Good job :)

2020-10-03 15:03 UTC, JorisWeeda approved these changes
56 commits = :fire:

2020-10-03 18:02 UTC, merged