Gait selection develop
project-march/march-iv pull request #583
Opened 2020-08-25 15:09 UTC by Olavhaasie

Closes PM-474

## Description
This is the *very big* PR that was coming for a long time now. Every change in this PR have been approved as separate steps, but it's nice to test everything together.

The build is unfortunately failing, because it uses the develop version of the downstream packages: monitor and simulation, which do not have the necessary changes.

## Changes
Some of the most important changes
* Removed `march_state_machine` and `march_gait_scheduler` package in favor of integrating those functionalities into the gait selection
* Gait state machine is generated on startup
* Gaits use graph descriptions in their configuration file to describe behavior
* No more intermediate action servers, instead 2 new topics
  - `CurrentGait` publishes details about every performed gait/subgait
  - `CurrentState` publishes the current state the state machine is in
* Gaits can now implement a `GaitInterface` to perform gaits instead of only preprogrammed trajectories

## Related PRs
* https://github.com/project-march/monitor/pull/68
* https://github.com/project-march/simulation/pull/63
* https://github.com/project-march/gait-files/pull/212

## Testing
Checkout the other PRs and start experimenting

2020-08-25 16:54 UTC, RutgerVanBeek requested changes
Mainly just questions

2020-08-25 16:54 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        self._current_subgait = self._default_walk.graph.start_subgaits()[0]
Shouldn't you set the duration here as well.

2020-08-25 16:54 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/state_machine/gait_interface.py
> +        return None
```suggestion
        """Returns the name of the currently executed trajectory."""
        return None
```

2020-08-25 16:54 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/state_machine/gait_state_machine.py
> +            self._should_stop = False
Shouldn't you keep this True if stop is rejected?

2020-08-25 16:54 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/state_machine/state_machine_input.py
> +        return TransitionRequest.NONE
Aren't you always returning the same integer here? Or is this for modularity?

2020-08-25 16:54 UTC, RutgerVanBeek commented on march_gait_selection/src/march_gait_selection/state_machine/trajectory_scheduler.py
> +        goal = FollowJointTrajectoryGoal()
It is nice to also set the stamp

2020-08-25 18:08 UTC, RutgerVanBeek commented
![Screenshot from 2020-08-25 20-05-12](https://user-images.githubusercontent.com/51922475/91211130-8da23e00-e70e-11ea-80cb-49a54218c0ab.png)
This happend while doing tilted path left start. However I could not reproduce this. 

Furthermore there is a lot more info in the terminal, what do we think about that, is it too spammy? @Roelemans @JorisWeeda

2020-08-26 07:36 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/state_machine/state_machine_input.py
> +        return TransitionRequest.NONE
I don't really understand your question. It returns an enum, which depends on the transition index, when there is no transition it always returns `NONE`

2020-08-26 07:42 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/state_machine/gait_state_machine.py
> +            self._should_stop = False
No otherwise it will still be True when the gait ends and you start a new gait. Furthermore, a gait rejects stop when it is not possible to stop the gait at all.

2020-08-26 12:30 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/dynamic_gaits/balance_gait.py
> +        self._current_subgait = self._default_walk.graph.start_subgaits()[0]
Oopsie this quite a big mistake and I have no idea how this actually works

2020-08-26 12:38 UTC, Olavhaasie commented on march_gait_selection/src/march_gait_selection/state_machine/trajectory_scheduler.py
> +        goal = FollowJointTrajectoryGoal()
The stamp in this message is used for planning the trajectory, when I add the current time here it will complain that the time of the first point is in the past. So it should be set to 0.

2020-08-27 07:20 UTC, JorisWeeda commented
> Furthermore there is a lot more info in the terminal, what do we think about that, is it too spammy? @Roelemans @JorisWeeda

I don't really mind the extra information. Compared to the old state machine it only has some additional information at the start and end of the gait (requested, accepted, executed).

2020-08-27 10:25 UTC, RutgerVanBeek approved these changes, later dismissed

2020-08-31 07:55 UTC, Roelemans requested changes
I have found two flaws:
1) You are able to change versions of a gait while that gait is being executed. This results in a midgait transition from, for example, "MV_walk_leftswing_v2" to "MIV_final" version of right swing, even though these subgait versions do not necessarily connect.
2) You are able to change versions such that gait transitions are no longer correct. This is possbile with both the bend_knee_left_tilted_path gait and the walk gait (when I created a new version of right open where the start did not match with standing, it allowed me to change it and execute it without problems)  

Ideally, to solve 1), you would allow changing only subgait versions of the gaits that are not currently being executed. However, you can also just disallow all version changes while not idle.

2020-09-05 11:15 UTC, Olavhaasie commented
> You are able to change versions of a gait while that gait is being executed. This results in a midgait transition from, for example, "MV_walk_leftswing_v2" to "MIV_final" version of right swing, even though these subgait versions do not necessarily connect.

Fixed this as you suggested by disallowing changing subgait versions of active gaits.

> You are able to change versions such that gait transitions are no longer correct. This is possbile with both the bend_knee_left_tilted_path gait and the walk gait (when I created a new version of right open where the start did not match with standing, it allowed me to change it and execute it without problems)

This is very good that you noticed this, since I forgot to implement checking changing subgait versions that are connected to `start` or `end`. I have now added two extra checks that make sure the new subgait version has the same positions, so that the state machine does not have to be re-generated. In the future you could of course build a way of notifying the state machine of such a change and re-generate the state machine.

2020-09-07 19:41 UTC, Roelemans requested changes
Nice job! One last thing :innocent: 
![image](https://user-images.githubusercontent.com/47626418/92414034-d87e7580-f152-11ea-9a00-757b978a2398.png)

2020-09-07 19:41 UTC, Roelemans commented on march_shared_classes/src/march_shared_classes/gait/gait.py
> +                            'The final position of new version {gait} {subgait} does not match'.format(
```suggestion
                            msg='The final position of new version {gait} {subgait} does not match'.format(
```

2020-09-07 19:41 UTC, Roelemans commented on march_shared_classes/src/march_shared_classes/gait/gait.py
> +                            'The starting position of new version {gait} {subgait} does not match'.format(
```suggestion
                            msg='The starting position of new version {gait} {subgait} does not match'.format(
```

2020-09-09 15:09 UTC, RutgerVanBeek requested changes
Is it on purpose that the time is not automatically running, when starting? I would prefer it do so.

2020-09-09 15:09 UTC, RutgerVanBeek commented on march_shared_classes/src/march_shared_classes/gait/subgait.py
> +        return dict([(joint.name, joint.setpoints[0].position) for joint in self.joints])
```suggestion
        return {joint.name: joint.setpoints[0].position for joint in self.joints}
```
It think this is the prettier way to do it.

2020-09-09 15:09 UTC, RutgerVanBeek commented on march_shared_classes/src/march_shared_classes/gait/subgait.py
> +        return dict([(joint.name, joint.setpoints[-1].position) for joint in self.joints])
```suggestion
        return {joint.name: joint.setpoints[-1].position for joint in self.joints}
```

2020-09-14 09:55 UTC, Olavhaasie commented
> Is it on purpose that the time is not automatically running, when starting? I would prefer it do so.
Do you mean that the simulation is paused? Because that should not be the default

2020-09-14 10:01 UTC, Roelemans approved these changes

2020-09-14 15:28 UTC, RutgerVanBeek commented
> > Is it on purpose that the time is not automatically running, when starting? I would prefer it do so.
> 
> Do you mean that the simulation is paused? Because that should not be the default

Last time I also wanted to test balance and checked out Roel's turn-off-com-branch, because of that didn't default to unpause. So it actually was allright when I check out the right branch in simulation now.

2020-09-14 15:28 UTC, RutgerVanBeek approved these changes

2020-09-16 09:05 UTC, merged