Add simple check for existence of gait directory
project-march/march-iv pull request #585
Opened 2020-08-27 12:42 UTC by KatjaSchmahl

Closes PM-235

## Description

Check whether the gait directory exists and give an extra warning that is more specific than FileNotFound of default.yaml.
## Changes

## Testing
A test for this fix was already present

2020-08-27 13:16 UTC, JorisWeeda requested changes
It would be nice to add a small test to verify the exception.

2020-08-27 13:18 UTC, JorisWeeda commented
> It would be nice to add a small test to verify the exception.

2020-08-27 13:23 UTC, JorisWeeda approved these changes
> It would be nice to add a small test to verify the exception.

I've noticed that there are indeed some tests which already verify the FileNotFoundError & PackageNotFoundError exception. So the comment above can be ignored.

2020-09-01 07:42 UTC, Roelemans approved these changes

2020-09-01 07:42 UTC, merged