Feature: Update pid gains when different
project-march/march-iv pull request #586
Opened 2020-09-13 15:35 UTC by RutgerVanBeek

No issue for this
## Description

Previously the interpolation was only started when a gait with a different gait type was selected. I have improved upon this by updating whenever the current and desired are not equal. This is beneficial when you update the parameters during runtime. When you select the next gait an interpolation towards the new values is done even when the gait type is equal. 

## Changes

* Create a function to test whether interpolation is necessary. 
* Check whether the needed gains are equal to current gains before interpolating
## Testing

One should launch the simulation with the parameter `gain_scheduling` set equal to true. One can update the parameter values with `rosparam load [path to valid yaml] /march/gain_scheduling_node`. It should start interpolating even when the gait types are equal.

2020-09-14 06:35 UTC, Roelemans requested changes

2020-09-14 06:35 UTC, Roelemans commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +            self.load_current_gains()
```suggestion
```
This seems redundant

2020-09-14 06:35 UTC, Roelemans commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +        if not self.interpolation_done:
self.interpolation_done no longer needs to be a class variable, as it is only used within this method.
```suggestion
        if not interpolation_done:
```

2020-09-14 15:42 UTC, Roelemans requested changes

2020-09-14 15:42 UTC, Roelemans commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +        # self.interpolation_done = True
```suggestion
```
:eyes:

2020-09-14 20:01 UTC, RutgerVanBeek commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +        # self.interpolation_done = True
Oh wow

2020-09-18 07:35 UTC, Roelemans requested changes

2020-09-18 07:35 UTC, Roelemans commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +        if not interpolation_done:
```suggestion
        if not self.done_interpolation_test(needed_gains):
```

2020-09-18 07:35 UTC, Roelemans commented on march_gain_scheduling/src/march_gain_scheduling/dynamic_pid_reconfigurer.py
> +        interpolation_done = self.done_interpolation_test(needed_gains)
```suggestion
```

2020-09-22 07:57 UTC, Roelemans approved these changes

2020-09-23 09:07 UTC, Olavhaasie approved these changes

2020-09-23 12:49 UTC, JorisWeeda approved these changes
:fire:

2020-09-23 13:33 UTC, merged